name = "PoVRay"
uuid = "c541ced5-0d8d-4f69-9e0a-22132a8930cb"
authors = ["Julian Kern"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
